import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Brands from './components/Brands';
import Footer from "./components/Footer";
import Overview from "./components/Overview";
import TherapeuticAreas from "./components/TherapeuticAreas ";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
       
          <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-1">{children}</main>
            {/* Use ConditionalFooter  instead if needed <ConditionalFooter /> */}
             <Brands />
             <TherapeuticAreas/>

            <Overview />
            
            <Footer />

           
          </div>
      </body>
    </html>
  );
}
